version: "3.9"

services:

  backend:
    build:
      context: ./Backend/app
    container_name: nest-backend

    ports:
      - "3000:3000"

    restart: unless-stopped

    environment:
      PORT: "3000"
      DB_PATH: /app/data.sqlite
      UPLOAD_DIR: /app/uploads
      FRONTEND_URL: http://localhost:4200

    volumes:
      - sqlite_data:/app/data
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./Frontend
      args:
        BUILD_CONFIGURATION: docker
    container_name: angular-frontend

    ports:
      - "4200:80"

    restart: unless-stopped

    depends_on:
      - backend

volumes:
  sqlite_data:
  uploads_data: